# Generated by Django 3.2.4 on 2021-07-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vetoffice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='phone',
            field=models.CharField(default='123-456-7890', max_length=30),
        ),
    ]
